HairSaloonWeb/Areas/Admin/Controllers/AdminAppointmentController.cs
using HairSaloon.DataAccess.Data;
using HairSaloon.DataAccess.Repository.IRepository;
using HairSaloon.Models;
using HairSaloon.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HairSaloonWeb.Areas.Customer.Controllers;

[Area("Admin")]
public class AdminAppointmentController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    private readonly UserManager<ApplicationUser> _userManager;

    private readonly ApplicationDbContext _db;

    public AdminAppointmentController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, ApplicationDbContext db)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _db = db;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var appointments = _unitOfWork.Appointments.GetAll();
        return View(appointments);
    }

    [HttpGet]
    public IActionResult Details(int? id)
    {
        if (id == null || id == 0)
            RedirectToAction("Index");

        Appointment appointment = _unitOfWork.Appointments.Get(x => x.Id == id, includeProperties: "Employee,Service");

        AppointmentVM vm = new(appointment);
        vm.Service = appointment.Service;
        vm.Employee = appointment.Employee;

        return View(vm);
    }

    [HttpGet]
    public async Task<IActionResult> Update(int? id)
    {
        if (id == null || id == 0)
            RedirectToAction("Index");

        Appointment appointment = _unitOfWork.Appointments.Get(x => x.Id == id, includeProperties: "Employee,Service");
        IEnumerable<Service> services = _unitOfWork.Services.GetAll();
        IEnumerable<ApplicationUser> employees = await _userManager.GetUsersInRoleAsync("Employee");

        ViewBag.Services = services.Select(s => new SelectListItem
        {
            Value = s.Id.ToString(),
            Text = s.Name
        }).ToList();

        ViewBag.Employees = employees.Select(s => new SelectListItem
        {
            Value = s.Id.ToString(),
            Text = $"{s.FirstName} {s.LastName}"
        }).ToList();

        ViewBag.AvailableHours = GetAvailableHoursList(appointment.Date, appointment.EmployeeId);

        AppointmentVM vm = new(appointment);
        vm.Service = appointment.Service;
        vm.Employee = appointment.Employee;

        return View(vm);
    }

    [HttpPost]
    public IActionResult Update(Appointment appointment, string date, string time)
    {
        if (ModelState.IsValid)
        {
            DateTime dateTime = DateTime.Parse($"{date} {time}");
            appointment.Date = dateTime;
            _unitOfWork.Appointments.Update(appointment);
            _unitOfWork.Save();

            TempData["success"] = "Appointment created successfully";
            return RedirectToAction("Index");

        }
        return RedirectToAction("Index");
    }


    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        List<Appointment> appointmentList = _unitOfWork.Appointments.GetAll(includeProperties: "Employee,Service").ToList();
        return Json(new { data = appointmentList });
    }

    [HttpGet]
    public IEnumerable<string> GetAvailableHoursList(DateTime? date, string employeeId)
    {
        IEnumerable<Appointment> appointments = _unitOfWork.Appointments.GetAll(
            e => e.EmployeeId == employeeId && EF.Functions.DateDiffDay(e.Date, date) == 0);

        var occupiedHours = appointments.Select(a => a.Date.ToString("HH:mm"));
        IEnumerable<string> hours = new List<string>
        {
            "08:00", "08:30", "09:00","09:30",
            "10:00", "10:30","11:00","11:30",
            "12:00","12:30","13:00","13:30",
            "14:00","14:30","15:00"
        };
        IEnumerable<string> availableHours = hours.Except(occupiedHours);
        return availableHours.ToList();
    }


    [HttpGet]
    public IActionResult GetAvailableHours(DateTime? date, string employeeId)
    {
        IEnumerable<string> availableHours = GetAvailableHoursList(date, employeeId);
        return Json(new { data = availableHours });
    }


    [HttpDelete, ActionName("Delete")]
    public IActionResult Delete(int id)
    {
        Appointment? appointmentFromDb = _unitOfWork.Appointments.Get(s => s.Id == id);

        if (appointmentFromDb == null)
            return Json(new { success = false, message = "Wystąpił problem usuwania" });

        _unitOfWork.Appointments.Remove(appointmentFromDb);
        _unitOfWork.Save();

        return Json(new { success = true, message = "Pomyślnie usunięto element" });
    }

    #endregion
}

HairSaloonWeb/Areas/Admin/Views/AdminAppointment/Details.cshtml
@model AppointmentVM
@{
    ViewData["Title"] = "Dashboard";
}


<div class="border-0 mt-1 p-4">
    <div class="card-header bg-dark bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">SZCZEGÓŁY REZERWACJI</h2>
            </div>
        </div>
    </div>
    <div class="p-4 bg-light shadow">
        <div class="d-flex justify-content-start gap-1">
            <a class="btn btn-subtle" asp-controller="AdminAppointment" asp-action="Update" asp-route-id="@Model.Id"><i class="bi bi-pencil-square me-1"></i>Edycja</a>
        </div>
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="p-3">
                <div asp-validation-summary="None"></div>
                <div class="py-2 col-12">
                    <label asp-for="Service.Name" class="ms-2">Nazwa usługi</label>
                    <input asp-for="Service.Name" class="form-control border-1" disabled />
                </div>
                <div class="py-2 col-12">
                    <label asp-for="CustomerFirstName" class="ms-2">Imię klienta</label>
                    <input asp-for="CustomerFirstName" class="form-control border-1" disabled />
                </div>
                <div class="py-2 col-12">
                    <label asp-for="CustomerPhoneNumber" class="ms-2">Numer telefonu klienta</label>
                    <input asp-for="CustomerPhoneNumber" class="form-control border-1" disabled />
                </div>
                <div class="py-2 col-12">
                    <label asp-for="CustomerEmail" class="ms-2">Adres email klienta</label>
                    <input asp-for="CustomerEmail" class="form-control border-1" disabled />
                </div>
                <div class="py-2 col-12">
                    <label asp-for="Employee" class="ms-2">Pracownik</label>
                    <input asp-for="Employee" value="@($"{Model.Employee?.FirstName} {Model.Employee?.LastName}")" class="form-control border-1" disabled />
                </div>
                <div class="py-2 col-12">
                    <label asp-for="Date" class="ms-2">Data wizyty</label>
                    <input asp-for="Date" class="form-control border-1" disabled />
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <a asp-controller="AdminAppointment" asp-action="Index" asp-area="Admin" class="btn btn-outline-secondary border form-control">
                            Powrót do listy
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

HairSaloonWeb/Areas/Admin/Views/AdminAppointment/Index.cshtml
@model IEnumerable<Appointment>
@{
    ViewData["Title"] = "Dashboard";
}

<div class="py-4 m-0 p-md-4 m-md-4 bg-light shadow rounded-2">
	<div class="p-2 d-flex justify-content-between border-bottom">
        <h2>Lista rezerwacji</h2>
    </div>
    <div style="overflow-x:auto;">
        <table id="tblData" class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Nazwa usługi</th>
                    <th>Data</th>
                    <th>Godzina</th>
                    <th>Imie klienta</th>
					<th>Email klienta</th>
					<th>Nr. tel. klienta</th>
					<th>Pracownik</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

  @section Scripts {
      <script src="~/js/appointment.js"></script>
  }

HairSaloonWeb/Areas/Admin/Views/AdminAppointment/Update.cshtml
@model AppointmentVM
@{
    ViewData["Title"] = "Dashboard";
}


<div class="border-0 mt-1 p-4">
    <div class="card-header bg-dark bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">EDYCJA REZERWACJI</h2>
            </div>
        </div>
    </div>
    <div class="p-4 bg-light shadow">
        <div class="d-flex justify-content-start gap-1">
            <a class="btn btn-subtle" asp-controller="AdminAppointment" asp-action="Details" asp-route-id="@Model.Id"><i class="bi bi-x-square mx-1"></i>Zakończ edycje</a>
        </div>
        <form method="post" class="row">
            <input asp-for="Id" hidden />
            <div class="p-3">
                <div asp-validation-summary="None"></div>

                <div>
                    <label asp-for="ServiceId" class="form-label">Wybierz usługę</label>
                    <select asp-for="ServiceId" asp-items="ViewBag.Services" class="form-select">
                        <option value="">@Model.Service.Name</option>
                    </select>
                    <span asp-validation-for="ServiceId" class="text-danger"></span>
                </div>

                <div class="py-2 col-12">
                    <label asp-for="CustomerFirstName" class="ms-2">Imię klienta</label>
                    <input asp-for="CustomerFirstName" class="form-control border-1"  />
                    <span asp-validation-for="CustomerFirstName" class="text-danger"></span>
                </div>

                <div class="py-2 col-12">
                    <label asp-for="CustomerPhoneNumber" class="ms-2">Numer telefonu klienta</label>
                    <input asp-for="CustomerPhoneNumber" class="form-control border-1"  />
                    <span asp-validation-for="CustomerPhoneNumber" class="text-danger"></span>
                </div>

                <div class="py-2 col-12">
                    <label asp-for="CustomerEmail" class="ms-2">Adres email klienta</label>
                    <input asp-for="CustomerEmail" class="form-control border-1"  />
                    <span asp-validation-for="CustomerEmail" class="text-danger"></span>
                </div>

                <div>
                    <label asp-for="EmployeeId" class="form-label">Pracownik</label>
                    <select asp-for="EmployeeId" asp-items="ViewBag.Employees" class="form-select">
                        <option value="">@Model.Employee.FirstName @Model.Employee.LastName</option>
                    </select>
                    <span asp-validation-for="EmployeeId" class="text-danger"></span>
                </div>

                <div class="py-2 col-12">
                    <label for="date" class="ms-2">Data wizyty</label>
                    <input for="date" name="date" type="date" 
                        min="@DateTime.Now.AddDays(0).ToString("yyyy-MM-dd")"
                        max="@DateTime.Now.AddMonths(3).ToString("yyyy-MM-dd")"
                        value="@Model.Date.ToString("yyyy-MM-dd")"
                        class="form-control border-1" />
                </div>


                <div class="py-2 col-12">
                    <label for="time" class="ms-2">Godzina wizyty</label>
                    <select name="time" class="form-control border-1">
                        @foreach (var hour in ViewBag.AvailableHours)
                        {
                            <option value="@hour">@hour</option>
                        }
                    </select>
                </div>

                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Zatwierdź</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="AdminAppointment" asp-action="Index" asp-area="Admin" class="btn btn-outline-secondary border form-control">
                            Powrót do listy
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("input[name='Date']").on("change", function() {
                let selectedDate = $(this).val();
                let employeeId = $("select[name='EmployeeId']").val();
                if (!selectedDate) return;

                $.get(`/Admin/AdminAppointment/GetAvailableHours?date=${selectedDate}&employeeId=${employeeId}`, function(data) {
                    let timeSelect = $("select[name='Time']");
                    timeSelect.empty(); // Czyścimy poprzednie opcje

                    if (data.error) {
                        console.error(data.error);
                        return;
                    }

                    $.each(data.data, function (index, hour) { // <- poprawka
                        timeSelect.append(new Option(hour, hour));
                    });
                }).fail(function () {
                console.error("Błąd pobierania godzin");
                });
            })
        })
    </script>
}