HairSaloonWeb/Areas/Admin/Controllers/ServiceController.cs
using HairSaloon.DataAccess.Repository.IRepository;
using HairSaloon.Models;
using HairSaloon.Models.ViewModels;
using HairSaloon.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HairSaloonWeb.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class ServiceController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public ServiceController(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;

    }
    public IActionResult Index()
    {
        var services = _unitOfWork.Services.GetAll();
        return View(services);
    }

    public IActionResult Create()
        => View(new ServiceVM());

    [HttpPost, ActionName("Create")]
    public IActionResult Create(Service obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Services.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category created successfully";
            return RedirectToAction("Index");
        }
        return View();
    }

    public IActionResult Update(int? id)
    {
        if (id == null || id == 0)
            RedirectToAction("Create");

        Service obj = _unitOfWork.Services.Get(u => u.Id == id);
        ServiceVM serviceVM = new ServiceVM(obj);
        return View(serviceVM);
    }

    [HttpPost, ActionName("Update")]
    public IActionResult Update(Service obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Services.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category edited successfully";
            return RedirectToAction("Index");
        }
        return View();
    }

    #region API CALLS

    [HttpGet]
    public IActionResult GetAll()
    {
        List<Service> serviceList = _unitOfWork.Services.GetAll().ToList();
        return Json(new { data = serviceList });
    }

    [HttpDelete, ActionName("Delete")]
    public IActionResult Delete(int id)
    {
        Service? serviceFromDb = _unitOfWork.Services.Get(s => s.Id == id);

        if (serviceFromDb == null)
            return Json(new { success = false, message = "Wystąpił problem usuwania" });

        _unitOfWork.Services.Remove(serviceFromDb);
        _unitOfWork.Save();

        return Json(new { success = true, message = "Pomyślnie usunięto element" });
    }

    #endregion

}

HairSaloonWeb/Areas/Customer/Controllers/AppointmentController.cs
using HairSaloon.DataAccess.Data;
using HairSaloon.DataAccess.Repository.IRepository;
using HairSaloon.Models;
using HairSaloon.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HairSaloonWeb.Areas.Customer.Controllers;

[Area("Customer")]
public class AppointmentController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    //private readonly UserManager<ApplicationUser> _userManager; TODO
    private readonly UserManager<ApplicationUser> _userManager;

    private readonly ApplicationDbContext _db;

    public AppointmentController(IUnitOfWork unitOfWork, /*UserManager<ApplicationUser> userManager,*/UserManager<ApplicationUser> userManager, ApplicationDbContext db)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _db = db;
    }

    public async Task<IActionResult> Index()
    {
        IEnumerable<Service> services = _unitOfWork.Services.GetAll();
        IEnumerable<IdentityUser> employees = await _userManager.GetUsersInRoleAsync("Employee");
        ViewBag.Services = services;
        ViewBag.Employees = employees;
        AppointmentVM vm = new AppointmentVM();
        return View(vm);
    }

    [HttpPost]
    public IActionResult Create(Appointment obj)
    {
        if (ModelState.IsValid)
        {
            _unitOfWork.Appointments.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = "Appointment created successfully";
            return RedirectToAction("Index");
        }
        return RedirectToAction("Index");
    }

    #region API CALLS
    [HttpPost]
    public IActionResult GetAvailableHours([FromBody] AppointmentRequest request)
    {
        IEnumerable<Appointment> appointments = _unitOfWork.Appointments.GetAll(
            e => e.EmployeeId == request.EmployeeId && EF.Functions.DateDiffDay(e.Date, request.Date) == 0);

        var hours = appointments.Select(a => a.Date.ToString("HH:mm"));

        return Json(new { data = hours });
    }

    #endregion
}

HairSaloonWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HairSaloonWeb</title>
    <link rel="stylesheet" href="~/HairSaloonWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/sass/StyleSheet.min.css" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
	<link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<link href="~/lib/quill/quill.snow.css" rel="stylesheet" />
	<script src="~/lib/quill/quill.min.js"></script>

</head>
<body class="min-vh-100 d-flex flex-column">
    <header class="bg-white sticky-top shadow">
        <nav class="container-md navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom border-bottom-0">
            <div class="container-fluid">
                <a class="navbar-brand fs-2 font-labella" href="/"><span class="font-gold">La</span>Bella</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link fs-4" asp-area="Customer" asp-controller="Appointment" asp-action="Index">Rezerwacja</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-4" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link fs-4" asp-area="Admin" asp-controller="Service" asp-action="Index">Panel</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial.cshtml"/>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="d-flex flex-column flex-1" style="padding-bottom:60px;">
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted bg-light">
        <div class="container">
            &copy; 2024 - HairSaloonWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>